/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.google.gson.JsonObject;
import controllers.EscanerRed;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nelson
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        ip = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ip_address = new javax.swing.JTextPane();
        btn_ejecutar = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        text_ejecutar = new javax.swing.JLabel();
        btn_list_result = new javax.swing.JPanel();
        txt_btn1 = new javax.swing.JLabel();
        btn_favoritos = new javax.swing.JPanel();
        txt_btn2 = new javax.swing.JLabel();
        btn_permitidos = new javax.swing.JPanel();
        txt_btn3 = new javax.swing.JLabel();
        btn_no_permitidos = new javax.swing.JPanel();
        txt_btn4 = new javax.swing.JLabel();
        marco = new javax.swing.JPanel();
        page = new javax.swing.JLayeredPane();
        panel_resul = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_favoritos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_permitidos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel_no_permitidos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scanner Wifi v1.0");
        setName("main"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ip.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        ip.setText("Dirección IP");
        panel.add(ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 310, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));

        ip_address.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        ip_address.setText("192.168.0.1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(ip_address, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(ip_address, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 740, 50));

        btn_ejecutar.setBackground(new java.awt.Color(51, 153, 255));
        btn_ejecutar.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));
        btn_ejecutar.setForeground(new java.awt.Color(204, 204, 204));
        btn_ejecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ejecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventClickRun(evt);
            }
        });
        btn_ejecutar.setLayout(null);

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-play-38.png"))); // NOI18N
        icon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventClickRun(evt);
            }
        });
        btn_ejecutar.add(icon1);
        icon1.setBounds(10, 0, 40, 50);

        text_ejecutar.setBackground(new java.awt.Color(255, 255, 255));
        text_ejecutar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text_ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        text_ejecutar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_ejecutar.setText("Ejecutar");
        text_ejecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        text_ejecutar.setFocusable(false);
        text_ejecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        text_ejecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventClickRun(evt);
            }
        });
        btn_ejecutar.add(text_ejecutar);
        text_ejecutar.setBounds(60, 0, 80, 50);

        panel.add(btn_ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 170, 50));

        btn_list_result.setBackground(new java.awt.Color(51, 153, 255));
        btn_list_result.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));
        btn_list_result.setForeground(new java.awt.Color(204, 204, 204));
        btn_list_result.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_list_result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_list_resultMouseClicked(evt);
            }
        });
        btn_list_result.setLayout(new java.awt.CardLayout());

        txt_btn1.setBackground(new java.awt.Color(255, 255, 255));
        txt_btn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_btn1.setForeground(new java.awt.Color(255, 255, 255));
        txt_btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn1.setText("Lista de resultados");
        txt_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_btn1.setFocusable(false);
        txt_btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_btn1MouseClicked(evt);
            }
        });
        btn_list_result.add(txt_btn1, "card3");

        panel.add(btn_list_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, 30));

        btn_favoritos.setBackground(new java.awt.Color(51, 153, 255));
        btn_favoritos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));
        btn_favoritos.setForeground(new java.awt.Color(204, 204, 204));
        btn_favoritos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_favoritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_favoritosMouseClicked(evt);
            }
        });
        btn_favoritos.setLayout(new java.awt.CardLayout());

        txt_btn2.setBackground(new java.awt.Color(255, 255, 255));
        txt_btn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_btn2.setForeground(new java.awt.Color(255, 255, 255));
        txt_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn2.setText("Favoritos");
        txt_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_btn2.setFocusable(false);
        txt_btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_btn2MouseClicked(evt);
            }
        });
        btn_favoritos.add(txt_btn2, "card3");

        panel.add(btn_favoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 90, 30));

        btn_permitidos.setBackground(new java.awt.Color(51, 153, 255));
        btn_permitidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));
        btn_permitidos.setForeground(new java.awt.Color(204, 204, 204));
        btn_permitidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_permitidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_permitidosMouseClicked(evt);
            }
        });
        btn_permitidos.setLayout(new java.awt.CardLayout());

        txt_btn3.setBackground(new java.awt.Color(255, 255, 255));
        txt_btn3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_btn3.setForeground(new java.awt.Color(255, 255, 255));
        txt_btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn3.setText("Permitidos");
        txt_btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_btn3.setFocusable(false);
        txt_btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_btn3MouseClicked(evt);
            }
        });
        btn_permitidos.add(txt_btn3, "card3");

        panel.add(btn_permitidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 100, 30));

        btn_no_permitidos.setBackground(new java.awt.Color(51, 153, 255));
        btn_no_permitidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));
        btn_no_permitidos.setForeground(new java.awt.Color(204, 204, 204));
        btn_no_permitidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_no_permitidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_no_permitidosMouseClicked(evt);
            }
        });
        btn_no_permitidos.setLayout(new java.awt.CardLayout());

        txt_btn4.setBackground(new java.awt.Color(255, 255, 255));
        txt_btn4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_btn4.setForeground(new java.awt.Color(255, 255, 255));
        txt_btn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_btn4.setText("No permitidos");
        txt_btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_btn4.setFocusable(false);
        txt_btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_btn4MouseClicked(evt);
            }
        });
        btn_no_permitidos.add(txt_btn4, "card3");

        panel.add(btn_no_permitidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 120, 30));

        marco.setBackground(new java.awt.Color(255, 255, 255));
        marco.setLayout(new java.awt.BorderLayout());

        page.setToolTipText("");
        page.setLayout(new java.awt.CardLayout());

        panel_resul.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estado", "Nombre", "IP", "Dirección MAC", "Favorito", "Permitido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDoubleBuffered(true);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panel_resulLayout = new javax.swing.GroupLayout(panel_resul);
        panel_resul.setLayout(panel_resulLayout);
        panel_resulLayout.setHorizontalGroup(
            panel_resulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        panel_resulLayout.setVerticalGroup(
            panel_resulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resulLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        page.add(panel_resul, "card2");

        panel_favoritos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Panel 2");

        javax.swing.GroupLayout panel_favoritosLayout = new javax.swing.GroupLayout(panel_favoritos);
        panel_favoritos.setLayout(panel_favoritosLayout);
        panel_favoritosLayout.setHorizontalGroup(
            panel_favoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_favoritosLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_favoritosLayout.setVerticalGroup(
            panel_favoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_favoritosLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        page.add(panel_favoritos, "card3");

        panel_permitidos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Panel 3");

        javax.swing.GroupLayout panel_permitidosLayout = new javax.swing.GroupLayout(panel_permitidos);
        panel_permitidos.setLayout(panel_permitidosLayout);
        panel_permitidosLayout.setHorizontalGroup(
            panel_permitidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_permitidosLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_permitidosLayout.setVerticalGroup(
            panel_permitidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_permitidosLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        page.add(panel_permitidos, "card4");

        panel_no_permitidos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Panel 4");

        javax.swing.GroupLayout panel_no_permitidosLayout = new javax.swing.GroupLayout(panel_no_permitidos);
        panel_no_permitidos.setLayout(panel_no_permitidosLayout);
        panel_no_permitidosLayout.setHorizontalGroup(
            panel_no_permitidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_no_permitidosLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_no_permitidosLayout.setVerticalGroup(
            panel_no_permitidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_no_permitidosLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        page.add(panel_no_permitidos, "card5");

        marco.add(page, java.awt.BorderLayout.CENTER);

        panel.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 930, 350));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 660));

        setSize(new java.awt.Dimension(1020, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changePage(JPanel panel){
        page.removeAll();
        page.add(panel);
        page.repaint();
        page.revalidate();
    }
    private void txt_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_btn1MouseClicked
        changePage(panel_resul);
    }//GEN-LAST:event_txt_btn1MouseClicked

    private void btn_list_resultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_resultMouseClicked
        changePage(panel_resul);
    }//GEN-LAST:event_btn_list_resultMouseClicked

    private void txt_btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_btn2MouseClicked
        changePage(panel_favoritos);
    }//GEN-LAST:event_txt_btn2MouseClicked

    private void btn_favoritosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_favoritosMouseClicked
        changePage(panel_favoritos);
    }//GEN-LAST:event_btn_favoritosMouseClicked

    private void txt_btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_btn3MouseClicked
       changePage(panel_permitidos);
    }//GEN-LAST:event_txt_btn3MouseClicked

    private void btn_permitidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_permitidosMouseClicked
        changePage(panel_permitidos);
    }//GEN-LAST:event_btn_permitidosMouseClicked

    private void txt_btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_btn4MouseClicked
        changePage(panel_no_permitidos);
    }//GEN-LAST:event_txt_btn4MouseClicked

    private void btn_no_permitidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_no_permitidosMouseClicked
        changePage(panel_no_permitidos);
    }//GEN-LAST:event_btn_no_permitidosMouseClicked

    private void eventClickRun(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventClickRun
        String ip = ip_address.getText();
        ip = ip.substring(0, ip.length() - 1 );
        EscanerRed scanner = new EscanerRed();
        scanner.networkAddress = ip;
        scanner.tabla = jTable1;
        //EscanerRed.calRangeAddressIp();
        
        // Crear modelo de datos
        scanner.ActualizarTablaEnTiempoReal();
        //model.addRow(rowData);
        //jTable1.setModel(model);
    }//GEN-LAST:event_eventClickRun
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_ejecutar;
    private javax.swing.JPanel btn_favoritos;
    private javax.swing.JPanel btn_list_result;
    private javax.swing.JPanel btn_no_permitidos;
    private javax.swing.JPanel btn_permitidos;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel ip;
    private javax.swing.JTextPane ip_address;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel marco;
    private javax.swing.JLayeredPane page;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel_favoritos;
    private javax.swing.JPanel panel_no_permitidos;
    private javax.swing.JPanel panel_permitidos;
    private javax.swing.JPanel panel_resul;
    private javax.swing.JLabel text_ejecutar;
    private javax.swing.JLabel txt_btn1;
    private javax.swing.JLabel txt_btn2;
    private javax.swing.JLabel txt_btn3;
    private javax.swing.JLabel txt_btn4;
    // End of variables declaration//GEN-END:variables
}
